# Generated by Django 3.1.2 on 2020-10-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookappointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='issue',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
