# Generated by Django 3.1.2 on 2020-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookappointment', '0002_appointments_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
