# Generated by Django 3.1.2 on 2020-10-15 20:38

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to=forum.models.saveimage),
        ),
    ]
