# Generated by Django 3.1.2 on 2020-10-16 19:45

from django.conf import settings
from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_post_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=forum.models.saveimage),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
