# Generated by Django 3.1.2 on 2020-10-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20201017_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classes',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
