# Generated by Django 3.1.2 on 2020-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='classes',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
