# Generated by Django 3.1.2 on 2020-10-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='classes',
            field=models.CharField(max_length=50),
        ),
    ]
