# Generated by Django 3.1.2 on 2020-10-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20201017_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video_link',
            field=models.CharField(blank=True, default='None', max_length=5000, null=True),
        ),
    ]
